### ISSUE TITLE
ERROR Exception fetching pool info from

### ISSUE THREAD

**Issue by RustyCleaner** [Chia-Network/pool-reference#52]
What could be wrong with this ?
This is from Client pooling on testnet >

2021-06-07T06:06:18.443 farmer chia.farmer.farmer : ERROR Exception fetching pool info from http:// pooladdressblahblah. org, Cannot connect to host http:80 ssl:default [Temporary failure in name resolution]

This is from Pool Server >

ERROR:aiohttp.server:Error handling request
Traceback (most recent call last):
File "/home/chia/pool-reference/venv/lib/python3.8/site-packages/aiohttp/web_protocol.py", line 314, in data_received
messages, upgraded, tail = self._request_parser.feed_data(data)
File "aiohttp/_http_parser.pyx", line 546, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadStatusLine: 400, message="Bad status line 'invalid HTTP method"

Harvester is working, and we are getting points in gui-pool info. But we have this error on Client and Server side from logs.

**Comment by Djomla003** [comment]
@mariano54 @ChiaMineJP @seeden @eFishCent this looks like a DNS/CNAME problem right?

**Comment by tranquilo** [comment]
you must remove `http://` from the pool address. You can do so by editing it on the config and restarting the client.

**Comment by Djomla003** [comment]
> you must remove `http://` from the pool address. You can do so by editing it on the config and restarting the client.

did not help, removing the "http://" caused only more problems and we could not connect to the pool.
Any another hint?

**Comment by ChiaMineJP** [comment]
Seems config for testnet was not loaded properly.

In `config.yaml`, there should be entries like below
```yaml
# Just a sample configuration
pool:
  pool_list:
    - authentication_key_info_signature: 8fa411d3164d6d4fc1a5985ea474a853304fec99b93300e12e3b3e8fc16dea8834804eb3dfcee7181a59cd4e969ada0e119d7c8cc94f5c912280dc4cfdbadd9076b6393b135e35b182bcd4e13bf9216877a6033dd9f89c249981e83908c5a926
      authentication_public_key: 970e181ae45435ae696508a78012dc80548c334cf29676ea6ade7049eb9d2b9579cc30cb44c3fd68d35a250cfbc69e29
      authentication_public_key_timestamp: 1621854388
      owner_public_key: 84c3fcf9d5581c1ddc702cb0f3b4a06043303b334dd993ab42b2c320ebfa98e5ce558448615b3f69638ba92cf7f43da5
      target_signature: 95ae82302134489d68cf0890356fc2d360c3bda9c9f15a3111a6a776df073a2fc6194896f3196a10fba18bb9de8e4fae0caf08e49fe32786d35fe0538daf0ceb6f7ace9477440b9978589bcaa28690dded6e5a296b47bffe2db97c1c28c9d13c
      pool_payout_instructions: c2b08e41d766da4116e388357ed957d04ad754623a915f3fd65188a8746cf3e8
      pool_url: localhost
      singleton_genesis: ae4ef3b9bfe68949691281a015a9c16630fc8f66d48c19ca548fb80768791afa
      target_puzzle_hash: 344587cf06a39db471d2cc027504e8688a0a67cce961253500c956c73603fd58
```
Looked into your error message, it seems value of `pool_url` was unset.

Check that you actually loaded `config.yaml` for testnet7, not mainnet.
Don't forget to set env var with `export CHIA_ROOT="<homedir>/.chia/testnet7"`

Also, check you did follow the install/run instruction as described below:  
https://github.com/Chia-Network/pool-reference#install-and-run-testnet
